v0.1/mySite/dashboard/urls.py
# DEFINE IMPORTS
from django.urls import path
from . import views

# DEFINE APP NAME: 'dashboard'
app_name = 'dashboard'

# URL Paths Resolved within the list: 'urlpatterns'
urlpatterns = [
    path('', views.landing_redirect, name='welcome'),
    path('dashboard/', views.dashboard, name='home'),
    path('grasp-pdf/', views.upload_pdf, name='grasp-pdf')
]

'''
Made with ❤️
--------------------
BRANDEN VAN STADEN -
    All Rights Reserved | OCTOBER 2023
-------------------------------------
'''

v0.1/mySite/mySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('users/', include('users.urls'))
]

v0.1/mySite/users/urls.py
# DEFINE IMPORTS
from django.urls import path
from . import views

# DEFINE APP NAME: 'users'
app_name = 'users'

# URL Paths Resolved within the list: 'urlpatterns'
urlpatterns = [
    # USER REGISTRATION ROUTES
    path('auth/', views.login_user, name='login_user'),
    path('login/', views.login_view, name='login_view'),
    # USER REGISTRATION ROUTES
    path('register/', views.register_view, name='register_view'),
    path('create/', views.register_user, name='create_user'),
    # USER MANAGEMENT ROUTES
    path('profile/', views.profile_view, name='profile_view'),
    path('logout/', views.logout_view, name='logout_view'),

]

v0.1/mySite/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

class PDF(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()

v0.1/mySite/users/models.py
# Imports
from django.db import models
from django.contrib.auth.models import User

# START OF FILE: [users]: 'models.py'

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

'''CODE IMPLEMENTED & CONTRIBUTED BY: BRANDEN VAN STADEN'''

v0.1/mySite/dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
import io
from pypdf import PdfReader
import io
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from collections import Counter

def landing_redirect(request):
    return HttpResponseRedirect(reverse('dashboard:home'))

def dashboard(request):
    return render(request, 'dashboard.html')

def upload_pdf(request):
    if request.POST and request.FILES['pdf_file']:
        nlp = spacy.load("en_core_web_sm")

        pdf_file = request.FILES['pdf_file'].read()

        pdf_reader = PdfReader(io.BytesIO(pdf_file))

        num_pages = len(pdf_reader.pages)
        i = 0
        content = []

        text = pdf_reader.pages[1]            
        doc = nlp(text.extract_text())

        # Exclude stopwords... What ever that means?
        sentences = [sent for sent in doc.sents if sent.text not in STOP_WORDS]

        # Calculate the term frequency of words
        word_freq = Counter()
        for token in doc:
            word_freq[token.text] += 1

        # Calculate the sentence score based on term frequency
        sentence_scores = {}
        for sentence in sentences:
            for word in sentence:
                if word.text in word_freq:
                    sentence_scores[sentence] = sentence_scores.get(sentence, 0) + word_freq[word.text]

        # Sort sentences by score and get the top N sentences for summary
        summary_sentences = sorted(sentence_scores, key=sentence_scores.get, reverse=True)[:5]
        summary = ' '.join([sent.text for sent in summary_sentences])
        print(summary)
        return render(request, 'upload_pdf.html', {'content': summary})
    else:
        return render(request, 'upload_pdf.html')

v0.1/mySite/users/views.py
# DEFINE IMPORTS
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.models import User


# START OF FILE: [users]: 'views.py'

# [GET] > userLogin
def login_view(request):
    # Extract the message(if any)
    message = request.GET.get('message', '')
    # Check if user is authenticated
    if request.user.is_authenticated:
        # Redirect to profile using 'reverse'
        return HttpResponseRedirect(reverse('users:profile_view'))
    # Else function will returned login webpage(render)
    return render(request, 'userLogin.html', {'message': message})

# [POST] < userLogin
def login_user(request):
    username = request.POST['username']
    password = request.POST['password']    
    # Authorize user
    user = authenticate(username=username, password=password)
    # User is NOT Authenticated
    if user is None:
        # Update result parameter to pass to view
        error_message = "Invalid Username or Password!"
        # Construct reverse URL for Http Response Redirect
        return render(request, 'userLogin.html', {'error_message': error_message})
    else:
        # Login user 
        login(request, user)
        return HttpResponseRedirect(reverse('users:profile_view'))

# [GET] > userRegister 
def register_view(request):
    # Check if user is authenticated
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:logout_view') + '?error_message=You must be logged out in to register a new user.')
    return render(request, 'userRegister.html')

# [POST] > userRegister 
def register_user(request):
    raiseFlag = False

    while raiseFlag == False:
        if request.method == 'POST':
            # Fetch data from form
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')
        
        # Check if both password match
        if password != confirm_password:
            return HttpResponseRedirect(reverse('users:register_view') + f'?error_message=Make sure your password match!')
                
        try:
            # Create a New User instance and Set Attributes
            new_user = User.objects.create_user(username=username, password=password)
            # Set Firstname
            new_user.email = email
            # Set Is? - Staff
            new_user.is_staff = False
            # Set Is? - Superuser
            new_user.is_superuser = False
            # Save User to Database
            new_user.save()
            print("Successfully Added New User to Database")
            print(f"USERNAME - {username}\nPassword(op-sec) - {password}\nEmail - {email}")
            # Redirect User to Profile
            return HttpResponseRedirect(reverse('users:login_view'))   
        # Catch the exception
        except Exception as ex:            
            # Get the Error Message
            error_message = str(ex)
            # Redirect back to register with the error message
            return HttpResponseRedirect(reverse('users:register_view') + f'?error_message={error_message}')
        
# [GET] > userProfile
def profile_view(request):
    return render(request, 'userProfile.html')

# [GET] > userLogout & [POST] < userLogout
def logout_view(request):
#    if request.method == 'POST':
#        return HttpResponseRedirect(reverse('users:logout_user'))
#     # Extract the message from the query parameter
#    error_message = request.GET.get('error_message', '')    
#    # Pass the message to the template
    logout(request)
    return redirect(reverse('users:login_view'))
 

'''CODE IMPLEMENTED & CONTRIBUTED BY: BRANDEN VAN STADEN'''

v0.1/mySite/dashboard/templates/dashboard.html
<!--EXTEND FILE: '_base.html'-->
{% extends 'shared/_base.html' %}

<!--SET BROWSER TAB TITLE-->
{% block title %}DASHBOARD - GraspAI{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="d-flex gap-2 justify-content-center align-items-center">
            <h3 class="display-5">Hello {{ user.username|title }}
                <p class="fs-3"><em>What would you like to do today?</em></p>
                <hr>
            </h3>     
        </div>
        <div class="row gap-2">
            <div class="col">
                <a href="{% url 'dashboard:grasp-pdf' %}" class="link-underline link-underline-opacity-0">
                    <div class="card text-bg-dark mb-3">                
                        <div class="card-header">
                            <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-filetype-pdf" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM1.6 11.85H0v3.999h.791v-1.342h.803c.287 0 .531-.057.732-.173.203-.117.358-.275.463-.474a1.42 1.42 0 0 0 .161-.677c0-.25-.053-.476-.158-.677a1.176 1.176 0 0 0-.46-.477c-.2-.12-.443-.179-.732-.179Zm.545 1.333a.795.795 0 0 1-.085.38.574.574 0 0 1-.238.241.794.794 0 0 1-.375.082H.788V12.48h.66c.218 0 .389.06.512.181.123.122.185.296.185.522Zm1.217-1.333v3.999h1.46c.401 0 .734-.08.998-.237a1.45 1.45 0 0 0 .595-.689c.13-.3.196-.662.196-1.084 0-.42-.065-.778-.196-1.075a1.426 1.426 0 0 0-.589-.68c-.264-.156-.599-.234-1.005-.234H3.362Zm.791.645h.563c.248 0 .45.05.609.152a.89.89 0 0 1 .354.454c.079.201.118.452.118.753a2.3 2.3 0 0 1-.068.592 1.14 1.14 0 0 1-.196.422.8.8 0 0 1-.334.252 1.298 1.298 0 0 1-.483.082h-.563v-2.707Zm3.743 1.763v1.591h-.79V11.85h2.548v.653H7.896v1.117h1.606v.638H7.896Z"/>
                            </svg> Grasp Complex PDF Documents
                        </div>
                        <div class="card-body">
                        <h5 class="card-title">Upload PDF Documents</h5>
                        <p class="card-text">Search, Summarize and Analyze Complex PDF Document</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col">
                <a  class="link-underline link-underline-opacity-0 disabled">
                    <div class="card text-bg-dark mb-3">
                        <div class="card-header">Grasp Webpages or Entire Websites</div>
                        <div class="card-body">
                            <h5 class="card-title">coming soon...</h5>
                            <p class="card-text">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cone-striped" viewBox="0 0 16 16">
                                <path d="m9.97 4.88.953 3.811C10.159 8.878 9.14 9 8 9c-1.14 0-2.158-.122-2.923-.309L6.03 4.88C6.635 4.957 7.3 5 8 5s1.365-.043 1.97-.12zm-.245-.978L8.97.88C8.718-.13 7.282-.13 7.03.88L6.275 3.9C6.8 3.965 7.382 4 8 4c.618 0 1.2-.036 1.725-.098zm4.396 8.613a.5.5 0 0 1 .037.96l-6 2a.5.5 0 0 1-.316 0l-6-2a.5.5 0 0 1 .037-.96l2.391-.598.565-2.257c.862.212 1.964.339 3.165.339s2.303-.127 3.165-.339l.565 2.257 2.391.598z"/>
                                </svg>
                            </p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col">
                <a class="link-underline link-underline-opacity-0 disabled">
                    <div class="card text-bg-dark mb-3">
                        <div class="card-header">Grasp for Enterprises & Professionals</div>
                        <div class="card-body">
                        <h5 class="card-title">coming soon...</h5>
                        <p class="card-text">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cone-striped" viewBox="0 0 16 16">
                                <path d="m9.97 4.88.953 3.811C10.159 8.878 9.14 9 8 9c-1.14 0-2.158-.122-2.923-.309L6.03 4.88C6.635 4.957 7.3 5 8 5s1.365-.043 1.97-.12zm-.245-.978L8.97.88C8.718-.13 7.282-.13 7.03.88L6.275 3.9C6.8 3.965 7.382 4 8 4c.618 0 1.2-.036 1.725-.098zm4.396 8.613a.5.5 0 0 1 .037.96l-6 2a.5.5 0 0 1-.316 0l-6-2a.5.5 0 0 1 .037-.96l2.391-.598.565-2.257c.862.212 1.964.339 3.165.339s2.303-.127 3.165-.339l.565 2.257 2.391.598z"/>
                            </svg>
                        </p>
                        </div>
                    </div>
                </a>        
            </div>    
        </div>
    {% else %}
        <div class="d-flex gap-2 align-items-center justify-content-center">
            <p class="fs-4 text-danger">You must be logged in to continue...</p>
            <a class="btn btn-secondary btn-outline-info" href="{% url 'users:login_view' %}">LOGIN</a>
            <a class="btn btn-secondary btn-outline-info" href="{% url 'users:register_view'%}">SIGN UP</a>
        </div>
    {% endif %}
{% endblock %}

v0.1/mySite/dashboard/templates/upload_pdf.html
<!--EXTEND FILE: '_base.html'-->
{% extends 'shared/_base.html' %}

<!--SET BROWSER TAB TITLE-->
{% block title %}GRASP PDF - GraspAI{% endblock %}

{% block content %}    
    {% if content %}
        <p class="fs-3">Your PDF was successfully processed!</p>
        <p class="fs-4"><em>Click the buttons to see results...</em></p>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#summary">
            PDF Summary
        </button>
        <!-- Modal -->
        <div class="modal fade" id="summary" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="summary" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="summaryLabel">Your Summary</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <!-- Vertically centered scrollable modal -->
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" id="summary">
                    <p class="p-2">{{ content }}</p>
                </div> 
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-outline-danger">Report a Bug</button>
                </div>
            </div>
            </div>
           
        {% else %}
        <div class="d-flex gap-2 justify-content-center align-items-center"></div>
            <form method="post" enctype="multipart/form-data" action="{% url 'dashboard:grasp-pdf' %}">
                {% csrf_token %}
                <p class="fs-3">Please Upload a PDF Document to Continue...</p>
                <label for="pdf_file">CHOOSE FILE:</label>
                <input type="file" name="pdf_file" id="pdf_file">
                <input type="submit" value="SUBMIT>>">      
            </form>
        {% endif %}
    </div>
{% endblock %}

v0.1/mySite/users/templates/userLogin.html
<!--EXTEND FILE: 'base.html'-->
{% extends 'shared/base.html' %}

<!--SET BROWSER TAB TITLE-->
{% block title %}Login - GraspAI{% endblock %}

{% block content %}
<div class="container">
    <p class="fs-3 fw-bolder"></p>
</div>
<div class="p-2">
    <div class="row">
        <div class="col-12">
            <p class="fs-3 fw-bolder text-start">Login with Username</p>
        </div>
        <div class="col">
            <div class="border border-primary-subtle rounded">
                <!--LOGIC WHICH HANDLES USER'S THAT ARE LOGGED ALREADY-->
                {% if user.is_authenticated %}
                    <p class="display-5">You are already logged in!</p>
                    <a class="btn btn-outline-primary mb-3" href="{% url 'users:logout' %}">Logout?</a>
                    <a class="btn btn-outline-primary mb-3" href="{% url 'users:profile_view' %}">View Profile?</a>
                {% else %}
                    <!--REGISTER FORM-->
                    <form action="{% url 'users:login_user' %}" class="form-control align-items-center" method="post">
                        {% csrf_token %}                    
                        <div class="row gap-3">
                            <!--ERROR MESSAGE-->
                            {% if error_message %}
                            <div class="col-12">
                                <p class="cite text-danger-emphasis">
                                    <p class="bolder text-secondary"><em>You can try again or <a href="{% url 'users:register_view' %}">Register...</a></em></p>
                                </p>                            
                            </div>
                            {% endif %}
                            <!--USERNAME LABEL & INPUT TAGS-->
                            <div class="col-md-4 col-12">
                                <div class="mb-3">
                                    <label class="form-label" for="username">Username</label>
                                    <input type="text" class="form-control" name="username" placeholder="John Doe" required>
                                </div>
                            </div>
                            <!--PASSWORD LABEL & INPUT TAGS-->
                            <div class="col-md-4 col-12">
                                <div class="mb-3">
                                    <label class="form-label" for="password">Password</label>
                                    <input type="password" class="form-control" name="password" placeholder="**********" required>
                                </div>
                            </div>
                            <!--SUBMIT & ALTERNATIVE INPUT/BUTTON TAGS-->
                            <div class="col-12 align-items-end">
                                <div class="row g-3">
                                    <div class="col">    
                                        <input type="submit" class="btn btn-outline-primary mb-3" value="CONTINUE" />
                                        <a class="btn btn-outline-secondary mb-3" href="{% url 'users:register_view' %}" title="Create New User">Not Registered?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                {% endif %} 
            </div>
        </div>
    </div>
</div>
{% endblock %}

v0.1/mySite/users/templates/userLogout.html
<!--EXTEND FILE: 'base.html'-->
{% extends 'shared/base.html' %}

<!--SET BROWSER TAB TITLE-->
{% block title %}Logout - GraspAI{% endblock %}

{% block content %}
    <a href="{% url 'logout' %}" class="btn btn-outline-warning">LOGOUT</a>
    <a href="{% url 'users:profile_view' %}" class="btn btn-outline-info">PROFILE</a>
{% endblock%}

v0.1/mySite/users/templates/userProfile.html
<!--EXTEND FILE: 'base.html'-->
{% extends 'shared/base.html' %}

<!--SET BROWSER TAB TITLE-->
{% block title %}{{ user.username }} - GraspAI{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <p class="fs-3 fw-mediumn ms-2 mb-0">WELCOME, {{ user.username|title }}</p>
        <p class="fs-6 fw-light ms-2"><em>My Profile</em></p>

    </div>
    <div class="col">
        <div class="d-flex gap-2 mt-3 ms-3">
            <dl class="row">
                <dt class="col-12 underline">
                    <p class="fs-4 text-white">DETAILS</p>
                </dt>
                <dt class="col-sm-3">USERNAME</dt>
                <dd class="col-sm-9 text-truncate">{{ user.username|title }}</dd>
                <dt class="col-sm-3">EMAIL ADDRESS</dt>
                <dd class="col-sm-9 text-truncate">{{ user.email }}</dd>
                <dt class="col-sm-3">PASSWORD TOKEN</dt>
                <dd class="col-sm-9 text-truncate">{{ user.password }}</dd>
                <dd class="col-sm-9"><hr></dd>     
                <dd class="col-sm-9">
                    <dl class="row">
                        <dt class="col-sm-4"><a href="#0" title="Delete Profile(not implemented!)" class="btn btn-outline-danger disabled">Delete Profile</a></dt>
                        <dd class="col-sm-8"><a href="#0" class="btn btn-outline-info disabled" title="TBD">disabled</a></dd>
                    </dl>
                </dd>
            </dl>          
        </div>
        
        
    </div>
</div>
{% endblock%}

v0.1/mySite/users/templates/userRegister.html
<!--EXTEND FILE: 'base.html'-->
{% extends 'shared/base.html' %}

<!--SET BROWSER TAB TITLE-->
{% block title %}Register - GraspAI{% endblock %}

{% block content %}
<div class="p-2">
    <div class="row">
        <div class="col-12">
            <p class="fs-3 fw-bolder text-start">Registering New User</p>
        </div>
        <div class="col">
            <div class="border border-primary-subtle rounded">
                <!--LOGIC WHICH HANDLES USER'S THAT ARE LOGGED ALREADY-->
                {% if user.is_authenticated %}
                    <p class="display-5">You are already logged in!</p>
                    <a class="btn btn-outline-primary mb-3" href="{% url 'users:logout' %}">Logout?</a>
                    <a class="btn btn-outline-primary mb-3" href="{% url 'users:profile_view' %}">View Profile?</a>
                {% else %}
                    <!--REGISTER FORM-->
                    <form action="{% url 'users:create_user' %}" class="form-control align-items-center" method="post">
                        {% csrf_token %}                    
                        <div class="row gap-3">
                            <!--ERROR MESSAGE-->
                            {% if error_message %}
                            <div class="col-12">
                                <p class="cite text-danger-emphasis">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-asterisk" viewBox="0 0 16 16">
                                        <path d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z"/>
                                    </svg> {{ error_message }}
                                    <p class="bolder text-secondary"><em>You can try again or <a href="{% url 'users:register_view'%}">Register...</a></em></p>
                                </p>                            
                            </div>
                            {% endif %}
                            <!--USERNAME LABEL & INPUT TAGS-->
                            <div class="col-md-4 col-12">
                                <div class="mb-3">
                                    <label class="form-label" for="username">Username</label>
                                    <input type="text" class="form-control" name="username" placeholder="John Doe" required>
                                </div>
                            </div>
                            <!--EMAIL ADDRESS LABEL & INPUT TAGS-->
                            <div class="col-md-4 col-12">
                                <div class="mb-3">
                                    <label class="form-label" for="email">Email Address</label>
                                    <input type="email" class="form-control" name="email" placeholder="johndoe@example.com" required>
                                </div>
                            </div>
                            <!--PASSWORD LABEL & INPUT TAGS-->
                            <div class="col-md-4 col-12">
                                <div class="mb-3">
                                    <label class="form-label" for="password">Password</label>
                                    <input type="password" class="form-control" name="password" placeholder="**********" required>
                                </div>
                            </div>
                            <!--CONFIRM PASSWORD LABEL & INPUT TAGS-->
                            <div class="col-md-4 col-12">
                                <div class="mb-3">
                                    <label class="form-label" for="confirm_password">Confirm Password</label>
                                    <input type="password" class="form-control" name="confirm_password" placeholder="**********" required>
                                </div>
                            </div>
                            <!--SUBMIT & ALTERNATIVE INPUT/BUTTON TAGS-->
                            <div class="col-12 align-items-end">
                                <div class="row g-3">
                                    <div class="col">    
                                        <input type="submit" class="btn btn-outline-primary mb-3" value="CONTINUE" />
                                        <a class="btn btn-outline-secondary mb-3" href="{% url 'users:login_view' %}" title="LOGIN">Already Registered?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock%}